// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hclust2_gini
RObject hclust2_gini(RObject distance, RObject objects, RObject control);
RcppExport SEXP genie_hclust2_gini(SEXP distanceSEXP, SEXP objectsSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RObject >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< RObject >::type objects(objectsSEXP);
    Rcpp::traits::input_parameter< RObject >::type control(controlSEXP);
    __result = Rcpp::wrap(hclust2_gini(distance, objects, control));
    return __result;
END_RCPP
}
