# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.hclust2_gini <- function(distance, objects, control = NULL) {
    .Call(`_genie_hclust2_gini`, distance, objects, control)
}

