# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.hclust2_gini <- function(distance, objects, control = NULL) {
    .Call('genie_hclust2_gini', PACKAGE = 'genie', distance, objects, control)
}

.hclust2_nntest_single_approx <- function(distance, objects, control = NULL) {
    .Call('genie_hclust2_nntest_single_approx', PACKAGE = 'genie', distance, objects, control)
}

.hclust2_single_approx <- function(distance, objects, control = NULL) {
    .Call('genie_hclust2_single_approx', PACKAGE = 'genie', distance, objects, control)
}

.hclust2_single <- function(distance, objects, control = NULL) {
    .Call('genie_hclust2_single', PACKAGE = 'genie', distance, objects, control)
}

